apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  # 속성과 비슷한 키; 각 키는 간단한 값으로 매핑됨
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # 파일과 비슷한 키
  game.properties: "enemy.types=aliens,monsters\nplayer.maximum-lives=5    \n"
  user-interface.properties: "color.good=purple\ncolor.bad=yellow\nallow.textmode=true    \n"
