apiVersion: v1
kind: Namespace
metadata:
  name: dev-nginx # 네임스페이스 생성
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-nginx-dep
  namespace: dev-nginx
  labels:
    app: dev-nginx-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-nginx-dep
  template:
    metadata:
      labels:
        app: dev-nginx-dep
    spec:
      containers:
      - name: dev-nginx-dep
        image: nginx:latest
        ports:
        - containerPort: 80