apiVersion: v1
kind: ServiceAccount  # 서비스 계정
metadata:
  name: dev01  # 서비스 계정 이름 지정
  namespace: dev-nginx # namespace 지정
---
apiVersion: v1
kind: Secret
metadata:
  name: dev-nginx-token
  namespace: dev-nginx
  annotations:
    kubernetes.io/service-account.name: dev01 # 서비스 계정 이름과 동일하게 지정
type: kubernetes.io/service-account-token