apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-rolebinding
  namespace: dev-nginx
subjects: # 어떤 사용자 유형과 연결할지 결정
- kind: ServiceAccount # 위에서 설정한 계정의 kind와 동일하게 설정
  name: dev01 # ServiceAccount 에서 생성한 계정 이름 설정
  apiGroup: ""  # 핵심(Core) API Group 으로 설정(= apiVersion: v1)
roleRef:  # 사용자에게 할당할 Role
  kind: Role # Role 할당
  name: dev-role # 사용하려는 Role 이름 지정(04-2.general-role.yaml 에서의 이름과 동일하게 설정)
  apiGroup: rbac.authorization.k8s.io # API 지정