# PV 지정
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath-label  # PV 이름
  labels:
    location: local # Label 설정
spec:
  capacity:
    storage: 2Gi  # PV 용량 지정(이진법 접두어 방식)
  volumeMode: Filesystem  # Volume을 FileSystem 형식으로 지정
  accessModes:  # Volume의 읽기/쓰기 모드 지정
    - ReadWriteOnce # 노드 1대에만 Volume의 읽기/쓰기 가능
  persistentVolumeReclaimPolicy: Delete # PV 해제 시 초기화 옵션
  storageClassName: manual  # Storage Class가 있는 PV는 해당 Storate Class에 맞는 PVC만 연결
  hostPath: # PV의 Volume Plugin (예시 : hostPath)
    path: /tmp  # Mount를 수행할 로컬 서버 경로
---
# PVC 지정
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hostpatch-label  # PVC 이름
spec:
  accessModes:  # Volume의 읽기/쓰기 모드 지정
  - ReadWriteOnce # 노드 1대에만 Volume의 읽기/쓰기 가능
  volumeMode: Filesystem  # Volume을 FileSystem 형식으로 지정
  resources:
    requests:
      storage: 1Gi  # PVC 용량 지정(PV의 전체 용량 보다 작아야 함)
  storageClassName: manual  # Storage Class가 있는 PV는 해당 Storate Class에 맞는 PVC만 연결
  selector:
    matchLabels:
      location : local # PV의 Label과 동일하게 지정

# Label을 지정하는 다른 방법 (.spec.selector.matchLabels 대신 사용 가능)
# spec:
#   selector:
#     matchExpressions:
#     - {key: environment, operator: In, values: [dev]}
  