##### Deployment와 ClusterIP 동시 배포용 #####
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-clusterip
  labels:
    app: nginx-clusterip
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-clusterip
  template:
    metadata:
      labels:
        app: nginx-clusterip
    spec:
      containers:
      - name: nginx-clusterip
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
spec:
  type: ClusterIP               # IP 부여 방식을 ClusterIP로 지정
  selector:
    app: nginx-svc              # Deployment의 서비스 이름인 nginx-svc와 연동
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80