apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
spec:
  replicas: 1
  type: ClusterIP
  selector:
    matchLabels:
      app: nginx-svc
  containers:
  - name: nginx
    image: nginxdemos/hello
  ports:
  - protocol: tcp
    port: 80
    targetPort: 80