##### Deployment와 NodePort 동시 배포용 #####
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nodeport
  labels:
    app: nginx-nodeport
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-nodeport
  template:
    metadata:
      labels:
        app: nginx-nodeport
    spec:
      containers:
      - name: nginx-nodeport
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    app: nginx-svc    # Deployment의 서비스 이름인 nginx-svc와 연동
  ports:
  - protocol: TCP
    port: 80          # 내부 포트(기본 서비스 포트)
    targetPort: 80    # 내부 포트(서비스 포트 번호가 여러개일 때)
    NodePort: 30080   # 외부 포트