apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    app: nginx-nodeport
  ports:
  - protocol: TCP
    port: 80          # 내부 포트(기본 서비스 포트)
    targetPort: 80    # 내부 포트(서비스 포트 번호가 여러개일 때)
    NodePort: 30080   # 외부 포트