apiVersion: v1
kind: Service
metadata:
     name: nginx-nodeport-svc
spec:
  selector:
    app: nginx                            # Deployment 이름인 nginx와 연동
  type: NodePort                          # IP 부여 방식을 NodePort로 지정
  ports:
  - name: http                            # 포트의 서비스 이름 지정
  - protocol: TCP                         # 포트가 사용하는 프로토콜
    port: 80                              # 내부 포트(기본 서비스 포트)
    nodePort: 30080                       # 외부 포트