apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hodtname: nginx-app
      subdomain: sub-nginx
      dnsPolicy: ClusterFirst
      containers:
      - name: nginx
        image: nginxdemos/hello
        ports: 
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
     name: nginx-domain
spec:
  selector:
    app: nginx                            # Deployment 이름인 nginx와 연동
  type: NodePort                          # IP 부여 방식을 NodePort로 지정
  ports:
  - name: http                            # 포트가 사용하는 프로토콜(L7)
    protocol: TCP                         # 포트가 사용하는 프로토콜(L4)
    port: 80                              # 내부 포트(기본 서비스 포트)
    targetPort: 80                        # 내부 포트(추가 서비스 포트)
    nodePort: 30080                       # 외부 포트