apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-domain
  labels:
    app: busybox-domain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-domain
  template:
    metadata:
      labels:
        app: busybox-domain
    spec:
      hostname: app                   # Main Domain Address 지정
      subdomain: busybox-app            # Sub Domain Address 지정
      containers:
      - name: busybox-domain-container
        image: busybox:latest
        # Keep the container running
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        resources:
          requests:
            cpu: 30m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
