apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
spec:
  type: ClusterIP               # IP 부여 방식을 ClusterIP로 지정
  clusterIP: None               # Headless 방식 적용(ClusterIP를 지정하지 않음)
  selector:
    app: nginx                  # Deployment의 서비스 이름인 nginx와 연동
  ports:
  - protocol: TCP               # 포트가 사용하는 프로토콜
    port: 80                    # 내부 포트(기본 서비스 포트)
    targetPort: 80              # 내부 포트(서비스 포트 번호가 여러개일 때)