apiVersion: batch/v1                                        # API Version(batch/v1beta 아님)
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"                                   # Cron Schedule 지정
  jobTemplate:
    spec:
      template:
        spec:
          containers:                                       # 실행할 Container 지정
          - name: hello                                     # metadata.name과 동일
            image: busybox:1.28                             # 실행할 Container Image 지정(busybox : Linux 기반의 네트워크 명령 사용 시 주로 사용)
            imagePullPolicy: IfNotPresent
            command:                                        # Container 실행 시 사용할 명령 지정
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster  # 시간, 텍스트 글자 출력
          restartPolicy: OnFailure                          # Container 비정상 종료 시 자동 재시작 기능 활성화