apiVersion: v1
kind: Pod
metadata:
  name: annotations-demo
  annotations:
    manager: "Administrator"
    contact: "010-1234-5678"
    release-version: "v1.0"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
