apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
spec:
  type: LoadBalancer            # 기존 : NodePort
  ports:
  - name: "vote-service"
    port: 80
    targetPort: 80
#   nodePort: 31000             # LoadBalancer 방식으로 변경하기 때문에 주석 처리
  selector:
    app: vote
  
