apiVersion: v1
kind: Pod
metadata:
  name: limit-cpu-2
spec:
  containers:
  - name: limit-cpu-2
    image: vish/stress
    resources:
      limits:
        cpu: "100"
      requests:
        cpu: "100"

