apiVersion: v1
kind: Pod
metadata:
  name: limit-mem-1
spec:
  containers:
  - name: limit-mem-1
    image: polinux/stress
    resources:
      requests:
        memory: "100Mi" # 기준 MEM
      limits:
        memory: "200Mi" # 최대 MEM
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"] # stress TEST 수행(Container 시작 시 작동할 테스트)
