apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-tolerations-app
  labels:
    app: nginx-tolerations-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-tolerations-app
  template:
    metadata:
      labels:
        app: nginx-tolerations-app
    spec:
      containers:
      - name: nginx-tolerations-app
        image: nginx
        ports:
        - containerPort: 58000
      tolerations:
      - key: "key01"
        operator: "Equal"
        value: "value01"
        effect: "NoSchedule"

### operator = Exists인 경우 ###
  # tolerations
  # - key: "key01"
  #   operator: "Exists" 
