apiVersion: v1
kind: Pod
metadata:
  name: init-pod
  labels:
    app: init-pod
spec:
  initContainers:
  - name: init-container
    image: hello-world
    command: ['sh', '-c', 'sleep 2; echo hello-world!']
  containers:
  - name: service-container
    image: nginx:latest
    command: ['sh', '-c', 'echo hello-container! && sleep 1']
