apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  labels:
    app: sample-pod
spec:
  initContainers:
  - name: init-service1
    image: nginx:latest
    command: ['sh', '-c', 'sleep 2; echo hello-world!']
  containers:
  - name: init-service1
    image: nginx:latest
    command: ['sh', '-c', 'echo hello-container! && sleep 1']