apiVersion: v1
kind: Pod
metadata:
  name: resources-pod
  labels:
    app: resources-pod
spec:
  containers:
  - name: resources-pod
    image: registry.k8s.io/pause:2.0
    resources:
      requests:
        cpu: 0.1
        memory: 200M
      limits:
        cpu: 0.5
        memory: 1G
    ports:
    - containerPort: 8080
