apiVersion: v1
kind: Pod
metadata:
  name: resources-pod
  labels:
    app: resources-pod
spec:
  containers:
  - name: resources-pod
    image: registry.k8s.io/pause:2.0
    resources:
      requests:
        cpu: 100m
        mem: 100m
      limits:
        cpu: 200m
        mem: 100m
