apiVersion: v1
kind: Pod
metadata:
  name: limit-cpu-2
spec:
  containers:
  - name: limit-cpu-2
    image: vish/stress
    resources:
      limits:        # 최대 CPU 사용률(100%)
        cpu: "100"
      requests:      # 기본 CPU 사용률(100%)
        cpu: "100"
