apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment
  annotations:
    kubernetes.io/change-cause: version 1.25.3 # 변경할 디플로이먼트의 주석(CHANGE-CAUSE)
spec:
  replicas: 3 # 동시에 실행할 POD 수량
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx-deployment
        image: nginx:1.25.3 # 변경할 nginx의 이미지 버전 지정
        ports:
        - containerPort: 80 # POD가 실행할 서비스 포트 번호
