apiVersion: v1
kind: Service
metadata:                                   # 이름 지정
  name: nginx-statefulset-service
  labels:
    app: nginx-statefulset-service
spec:
  ports:
  - port: 80
    name: web                               # metadata.name 필드 값 지정
  clusterIP: None
  selector:
    app: nginx-statefulset-service
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web                                 # metadata.name 필드 값 지정
spec:
  selector:
    matchLabels:
      app: nginx-statefulset                # .spec.template.metadata.label과 같은 값
  serviceName: "nginx-statefulset-service"  # Statefulset 서비스 이름 지정
  replicas: 3 
  template:
    metadata:
      labels:
        app: nginx-statefulset              # .spec.template.metadata.label과 같은 값
    spec:
      terminationGracePeriodSeconds: 10     # GracePool 대기 시간 설정(실행 중인 프로세스 종료 시 정상 종료 할 수 있도록 대기)
      containers:
      - name: nginx-statefulset
        image: nginx
        ports:
        - containerPort: 80
          name: web