apiVersion: v1
kind: Service
metadata:
  name: nginx-beta-service
  namespace: nginx-label # 실습 편의를 위해 NS 구분
spec:
  type: ClusterIP
  selector:
    release: beta # Deployment의 Lable 에서 release가 'beta'인 항목들을 결합
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
