apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user  # 계정 ID 생성
  namespace: kubernetes-dashboard # dashboard 전용 namespace 지정
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user  # 계정 ID
  namespace: kubernetes-dashboard # dashboard 전용 namespace 지정